name: annotation_angular_router
description: An annotation based router for angular
version: 0.0.1-alpha

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: 4.0.0
  barback: ^0.15.2+2

dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.0

transformers:
  - angular:
     entry_points:
       - example/annotation_angular_router_example.dart
